### ISSUE TITLE
Admin Approval not sending an email

### ISSUE THREAD

**Issue by Jellyfish458** [readybytes/joomlaxi_adminapproval#17]
Hi Guys,

It seems pretty simple to set up

Installed the plug in
Enabled the plug in
Edited and added my email address for notification

It successfully block a new registrant, but I don't get an email?

What have I done wrong?

Regards

Jon

**Comment by gvdn** [comment]
Hi,

The Admin Approval add-in does not send an email to admin to approve the user.  It activates and enables the new user directly after the user activates the registration via the email he received.

Will you kindly look into this issue?
 
Regards
Geordie

Configuration Information (as requested):

Admin Approval Version:           3.4 (J2.5-3.x_Php5.3-5.4)
Installation File:                        adminapproval_3.4_J2.5-3.x_Php5.3-5.4

Plug-in Settings:
Apply Approval to:                    Joomla
Send approval email to:           [valid email address filled in]                       

System Information:
PHP Built On: 	                         Linux lnxwebs02.cpt.wa.co.za 2.6.32-531.29.2.lve1.3.11.1.el6.x86_64 #1 SMP Thu Dec 18 06:49:17 EST 2014 x86_64
Database Version: 	                 5.5.40-cll
Database Collation: 	                 latin1_swedish_ci
PHP Version: 	                         5.3.27
Web Server: 	                        Apache
WebServer to PHP Interface: 	cgi-fcgi
Joomla! Version: 	                Joomla! 3.3.6 Stable [ Ember ] 01-October-2014 02:00 GMT
Joomla! Platform Version: 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent: 	                        Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0

**Comment by rbsl-shakuntala** [comment]
Thanks for details..

Fixed the issue.. Please check the latest code..!!

**Comment by gvdn** [comment]
Tested and it works now on my system.

Thanks for the excellent support.

Regards
Geordie
